In [2]:
import pandas as pd
import random
def create_data():
    x1 = [random.random()*1000 for _ in range(10000)]
    x2 = [random.random()*1000 for _ in range(10000)]
    d = pd.DataFrame({'x1':x1,'x2':x2})
    d['y'] = d['x1']*3+d['x2']*4
    return d
d = create_data()
d

              x1          x2            y
0       7.931353  588.010623  2375.836554
1     901.716180  385.036394  4245.294116
2     992.668754    4.405123  2995.626753
3     460.712582  197.740235  2173.098686
4     741.202444  383.081495  3755.933311
...          ...         ...          ...
9995  592.368048  666.677046  4443.812329
9996  531.154299  651.395204  4199.043714
9997  628.598659  199.106744  2682.222951
9998  121.738993  411.342828  2010.588293
9999   93.320872  906.441536  3905.728761

[10000 rows x 3 columns]

In [ ]:
0-1000
random.random()*1000

1-1000; 0-999+1
random.random()*999+1

In [7]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
#minmaxScaler (x-min_)/(max_-min_)
#StandardScaler  (x-u)/var

def predict(x,w):
    y = (x*w[:-1]).sum(axis = 1)+w[-1]
    return y

def update_(y,target,x,w,lr):
    loss = ((y-target)**2).sum()/len(y)
    g_1 = (2*(y-target)*x[:,0]).mean()
    g_2 = (2*(y-target)*x[:,1]).mean()
    g_b = (2*(y-target)).mean()
    
    w[0] = w[0] - g_1 *lr
    w[1] = w[1] - g_2 *lr
    w[2] = w[2] - g_b*lr
    return w,loss
    

train = create_data()
test = create_data()
target = train['y']
traget_test = test['y']

mm = MinMaxScaler()
train = mm.fit_transform(train[['x1','x2']])
test = mm.transform(test[['x1','x2']])

batch_size = 10
lr = 10**-3
w = [0.1,0.1,0.1]

#y = w1*x1+w2*x2+b

for epo in range(100):
    for i in range(0,len(train),batch_size):
        x = train[i:i+batch_size]
#         train[0:10]
#         train[10:20]
#         train[20:30]
        y = predict(x,w)
        w,loss = update_(y,target[i:i+batch_size],x,w,lr)
    print(epo,loss)

0 804848.0672961896
1 609586.5157044649
2 490790.5548443567
3 395679.8070890599
4 319024.7404751359
5 257221.90449176365
6 207390.8677205138
7 167211.51843271466
8 134814.00865635692
9 108691.09974396016
10 87627.68488568431
11 70644.06877720702
12 56950.298536381975
13 45909.37937273704
14 37007.637570113635
15 29830.836059798097
16 24044.922046384047
17 19380.50578739204
18 15620.345769199921
19 12589.256918520612
20 10145.972090471889
21 8176.578411880977
22 6589.223541473158
23 5309.846058920766
24 4278.731829572565
25 3447.736567547632
26 2778.045746323296
27 2238.367935560905
28 1803.4777428393402
29 1453.040747640656
30 1170.6658874530326
31 943.1413001125222
32 759.8181321099414
33 612.1136840736319
34 493.1107999730751
35 397.23487216777255
36 319.9934369860292
37 257.76624181709343
38 207.63600926246932
39 167.25201522586957
40 134.72012349350885
41 108.51415001306809
42 87.40442271604229
43 70.4002033471971
44 56.70328347560305
45 45.67058760703445
46 36.78403626568355
47 29.626260548254912
48 23.861032713907843
49 19.217497537345956
50 15.477466663703444
51 12.465181313416384
52 10.039064057442326
53 8.085073387097856
54 6.5113497728922125
55 5.243902336236553
56 4.223133964774954
57 3.401041959043286
58 2.7389629366463173
59 2.2057562180643693
60 1.7763404662987419
61 1.4305149111570443
62 1.1520098320906438
63 0.927721725190495
64 0.7470972433215322
65 0.60163697851038
66 0.48449577987861253
67 0.39016083157174536
68 0.31419236571121817
69 0.2530148265516245
70 0.20374867128132235
71 0.1640749017781733
72 0.1321259591998452
73 0.10639785202787022
74 0.08567938594066862
75 0.06899516766577987
76 0.05555970241003094
77 0.04474042596692299
78 0.03602793264343759
79 0.029011998536654177
80 0.023362272189219466
81 0.01881272416525053
82 0.015149123887754311
83 0.012198954469637268
84 0.009823290961736094
85 0.0079102598090284
86 0.006369771697040847
87 0.005129279898788699
88 0.0041303644670858935
89 0.0033259814988689136
90 0.0026782479865903575
91 0.00215665798316255
92 0.0017366461007272914
93 0.0013984307214916017
94 0.0011260824560297225
95 0.0009067739931731643
96 0.0007301760219273406
97 0.000587970782876586
98 0.00047346034519127713
99 0.00038125116379707143

In [ ]:
loss = (y-target)**2

y = w1*x1+w2*x2+b

g_1 = @loss/@w1 = @loss/@y * @y/@w1 = 2*(y-target)*x1
g_2 = @loss/@w2 = @loss/@y * @y/@w2 = 2*(y-target)*x2
g_b = @loss/@b = 2*(y-target)

w1 = w1 - g_1*lr
w2 = w2 - g_2*lr
b = b - g_b*lr

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
y = w1*x1+w2*x2+b

In [9]:
import numpy as np
train = np.array([1,2,3,4,5,6,7,8,9,10])
batch_size = 2
for i in range(0,len(train),batch_size):
    x = train[i:i+batch_size]
    print(x)

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]

In [ ]:
(y-target)**2
(y-target)

In [10]:
w

[2999.143644535598, 3999.5502809412196, 0.5462946995851066]

In [18]:
preds = predict(test,w)
d_ =  pd.DataFrame({'preds':preds,'target':traget_test})
print(((d_['preds']-d_['target'])**2).mean())
d_

0.0003302144111583725

            preds       target
0     2630.293537  2630.281070
1     4921.125721  4921.141414
2     2758.832808  2758.817759
3     4638.203792  4638.214310
4     3852.710285  3852.707842
...           ...          ...
9995  2282.877681  2282.858555
9996  6120.640129  6120.671387
9997  2504.656980  2504.644907
9998  4589.449426  4589.461199
9999  4205.781584  4205.785533

[10000 rows x 2 columns]

In [19]:
from sklearn.linear_model import LinearRegression
import numpy as np
import random
from sklearn.preprocessing import StandardScaler,MinMaxScaler
def create_data():
    limit = 1000
    x1 = np.array([random.random()*1000 for _ in range(10000)])
    x2 = np.array([random.random()*1000 for _ in range(10000)])

    d = pd.DataFrame({'x1':x1,'x2':x2})
    d['y'] = d['x1']*3+d['x2']*4
    return d 
train = create_data()
test = create_data()

ss = MinMaxScaler()
target = train['y']
train = ss.fit_transform(train[['x1','x2']])
target_test = test['y']
test = ss.transform(test[['x1','x2']])

lr = LinearRegression()
lr.fit(train,target)
preds = lr.predict(test)
d = pd.DataFrame({'preds':preds,'target':target_test})
print(d)
print(lr.coef_)

            preds       target
0     3337.720726  3337.720726
1     3541.081935  3541.081935
2     3136.034477  3136.034477
3     3304.547222  3304.547222
4     2719.188921  2719.188921
...           ...          ...
9995  1816.419855  1816.419855
9996  3100.577421  3100.577421
9997  4622.454306  4622.454306
9998  5166.080087  5166.080087
9999  4103.152865  4103.152865

[10000 rows x 2 columns]
[2999.63651936 3999.29382587]